# Generated by Django 5.2.8 on 2025-11-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=20)),
                ('roll_name', models.CharField(max_length=20)),
                ('ref_num', models.IntegerField()),
                ('joining_date', models.DateField()),
            ],
        ),
    ]
